### PR TITLE
[k8s] Surface docker permission error for `sky local up`

### LINKED ISSUE #2592: [k8s] `sky local up` shows `Docker is not running` while docker is running
The CLI command `sky local up` shows following error:
```bash
$ sky local up                           
⠋ Creating local cluster...
Failed to create local cluster. Docker is not running. Please start Docker and try again.
```
After checking the scripts and manually run `docker info`, it seems like some permission issues:
```bash
$docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```

Shall we add `sudo` before the `docker` commands in the `sky/utils/kubernetes/create_cluster.sh`?

### PR DESCRIPTION
**Pull request by Shrinandan-N**
Fixes #2592. 

This pull request updates create_cluster.sh to enhance the handling of Docker permission errors. The revised script captures the output and error messages from `docker info`. It identifies and distinguishes between 'permission denied' errors and scenarios where Docker is not running, and alerts the user with an error message accordingly. 

Tested (run the relevant ones):

- [x] Code formatting: `bash format.sh`
- [x] Created test user without docker permission (not in docker group) and verified that a permission error was reported instead of the standard "Docker is not running" error.
- [x] Added test user to docker group and ran `sky local up` to ensure that permission error/docker error did not prevail after docker permissions were granted.

### CODE REVIEW

File: sky/utils/kubernetes/create_cluster.sh [hunk 1]
```diff
@@ -8,9 +8,20 @@ set -e
...
+set +e
+docker_output=$(docker info 2>&1)
+exit_status=$?
+set -e
+
+# Check if docker info command was successful
+if [ $exit_status -ne 0 ]; then
+    # Check for 'permission denied' in docker output
+    if echo "$docker_output" | grep -q "permission denied"; then
+        >&2 echo "Permission denied while trying to connect to the Docker daemon socket. Please ensure your user is added to the docker group or has appropriate permissions."
```
Comment (romilbhardwaj) [inline sky/utils/kubernetes/create_cluster.sh:21]: Minor nit

```suggestion
        >&2 echo "Permission denied while trying to connect to the Docker daemon socket. Make sure your user is added to the docker group or has appropriate permissions. Instructions: https://docs.docker.com/engine/install/linux-postinstall/"
```

**Review by romilbhardwaj — APPROVED** [review]
Awesome, thanks @Shrinandan-N! Left a minor comment, otherwise good to go!

**Comment by Shrinandan-N** [comment]
Sounds good @romilbhardwaj, accepted the commit suggestion!
